# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('frontend/dist/', 'front')],
    hiddenimports=[
        'service.syncJob.jobClient',
        'service.syncJob.jobService',
        'controller',
        'controller.jobController',
        'service',
        'service.syncJob',
        'aiohttp',
        'aiohttp.web',
        'aiohttp.web_response',
        'aiohttp.web_request',
        'aiohttp.client_exceptions',
        'aiohttp_cors',
        'json',
        'os',
        'sys',
        'time',
        'datetime',
        'threading',
        'logging',
        'asyncio',
        'multiprocessing',
        'concurrent.futures',
        'queue',
        'pathlib',
        'jinja2',
        'jinja2.ext',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='taoSync',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo.ico'],
)
